---
title: Botanic & Clay
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
    image: "/assets/img/card.jpg"
description: This isn't any old plant, it's your plant.
facebook:
  publisher: https://www.facebook.com/botanicandclay
  admins: 536540509
social:
  links:
  - https://www.facebook.com/botanicandclay
  - https://www.instagram.com/botanicandclay
gems:
- jekyll-seo-tag
permalink: pretty
