---
title: Botanic & Clay
description: This isn't any old plant, it's your plant.
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
facebook:
  publisher: https://www.facebook.com/botanicandclay
  admins: 536540509
defaults:
- scope:
    path: ''
  values:
    layout: default
    image: /assets/img/card.jpg
social:
  links:
    - https://www.facebook.com/botanicandclay
    - https://www.instagram.com/botanicandclay
gems:
- jekyll-seo-tag
permalink: pretty
